
server:
  port: 80
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://app1:7001/eureka/,http://app2:7002/eureka/,http://app3:7003/eureka/
feign:
  hystrix:
    enabled: true
spring:
  application:
    name: fegin-client